// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { Draft } from "../../schemas/Draft.js";
import { Revision } from "../../schemas/Revision.js";

/** What `submit` receives, after the membrane has asserted it. */
export const submitInput = Draft;
export type submitInput = z.infer<typeof submitInput>;

/** What `submit` must return. Throw to decline. */
export const submitOutput = Revision;
export type submitOutput = z.infer<typeof submitOutput>;

export type submitFn = (p: submitInput) => submitOutput;
