// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { FactReport } from "../../schemas/FactReport.js";
import { ReviewNote } from "../../schemas/ReviewNote.js";
import { StyleReport } from "../../schemas/StyleReport.js";

/** What `verdict` receives, after the membrane has asserted it. */
export const verdictInput = z.object({
  "StyleReport": StyleReport,
  "FactReport": FactReport,
});
export type verdictInput = z.infer<typeof verdictInput>;

/** What `verdict` must return. Throw to decline. */
export const verdictOutput = ReviewNote;
export type verdictOutput = z.infer<typeof verdictOutput>;

export type verdictFn = (p: verdictInput) => verdictOutput;
