// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { Accepted } from "../../schemas/Accepted.js";
import { Revision } from "../../schemas/Revision.js";

/** What `revise` receives, after the membrane has asserted it. */
export const reviseInput = Revision;
export type reviseInput = z.infer<typeof reviseInput>;

/** What `revise` must return. Throw to decline. */
export const reviseOutput = z.discriminatedUnion("edge", [
  z.object({ edge: z.literal("Accepted"), payload: Accepted }),
  z.object({ edge: z.literal("Revision"), payload: Revision }),
]);
export type reviseOutput = z.infer<typeof reviseOutput>;

export type reviseFn = (p: reviseInput) => reviseOutput;
