// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { Revision } from "../../schemas/Revision.js";
import { StyleReport } from "../../schemas/StyleReport.js";

/** What `checkStyle` receives, after the membrane has asserted it. */
export const checkStyleInput = Revision;
export type checkStyleInput = z.infer<typeof checkStyleInput>;

/** What `checkStyle` must return. Throw to decline. */
export const checkStyleOutput = StyleReport;
export type checkStyleOutput = z.infer<typeof checkStyleOutput>;

export type checkStyleFn = (p: checkStyleInput) => checkStyleOutput;
