// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { NormalizedParcel } from "../../schemas/NormalizedParcel.js";
import { ParcelIdentity } from "../../schemas/ParcelIdentity.js";
import { TownshipLookup } from "../../schemas/TownshipLookup.js";

/** What `resolveIdentity` receives, after the membrane has asserted it. */
export const resolveIdentityInput = z.object({
  "NormalizedParcel": NormalizedParcel,
  "TownshipLookup": TownshipLookup,
});
export type resolveIdentityInput = z.infer<typeof resolveIdentityInput>;

/** What `resolveIdentity` must return. Throw to decline. */
export const resolveIdentityOutput = ParcelIdentity;
export type resolveIdentityOutput = z.infer<typeof resolveIdentityOutput>;

export type resolveIdentityFn = (p: resolveIdentityInput) => resolveIdentityOutput;
