// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { NormalizedParcel } from "../../schemas/NormalizedParcel.js";
import { ParcelCentroid } from "../../schemas/ParcelCentroid.js";

/** What `parcelCentroid` receives, after the membrane has asserted it. */
export const parcelCentroidInput = NormalizedParcel;
export type parcelCentroidInput = z.infer<typeof parcelCentroidInput>;

/** What `parcelCentroid` must return. Throw to decline. */
export const parcelCentroidOutput = ParcelCentroid;
export type parcelCentroidOutput = z.infer<typeof parcelCentroidOutput>;

export type parcelCentroidFn = (p: parcelCentroidInput) => parcelCentroidOutput;
