// GENERATED by `weir scaffold parcelCentroid` — do not edit.
// Edit parcelCentroid.ts. Re-run the scaffold to pick up declaration changes.
import { isDeepStrictEqual } from "node:util";

export interface PropertyCheck {
  name: string;
  holds: (input: unknown, output: unknown) => boolean;
}

export interface Failure {
  example: number;
  stage: "input-schema" | "output-schema" | "value" | "threw" | "property";
  detail: string;
}

/** The gate's own comparison (node:util's isDeepStrictEqual), not a looser one. */
const same = (a: unknown, b: unknown): boolean => isDeepStrictEqual(a, b);

/**
 * Resolves a dotted path against { input, output }, the way property.ts does:
 * `input.age` for a single input, `input.Person.age` for an allOf bag, and
 * `output.edge` / `output.payload.x` for a tagged oneOf result. A path that
 * runs off the end throws rather than yielding undefined — a path that cannot
 * resolve is a broken property, not a failing one.
 */
const reader = (input: unknown, output: unknown) => (path: string): unknown => {
  const segments = path.split(".");
  const root = segments[0];
  if (root !== "input" && root !== "output") {
    throw new Error(`path "${path}" must start with "input" or "output".`);
  }
  let current: unknown = root === "input" ? input : output;
  for (const segment of segments.slice(1)) {
    if (typeof current !== "object" || current === null) {
      throw new Error(`path "${path}" does not resolve: "${segment}" has nothing to read from.`);
    }
    if (!Object.hasOwn(current as Record<string, unknown>, segment)) {
      throw new Error(`path "${path}" does not resolve: no "${segment}" here.`);
    }
    current = (current as Record<string, unknown>)[segment];
  }
  return current;
};

import fn from "./parcelCentroid.js";
import { parcelCentroidInput, parcelCentroidOutput } from "./schema.js";

/** The node's declared examples, in runtime form. */
export const examples: { given: unknown; expect: unknown }[] = [
  { given: {"pin":"10-003-013-20","county":"Osceola","townshipFromSource":"Middle Branch","acres":3.755,"boundaryJson":"{\"type\":\"Polygon\",\"coordinates\":[[[0,0],[0,2],[2,2],[2,0],[0,0]]]}","provenance":"verified","vintageAsOf":"2026-08-30","vintageSourceType":"continuous","vintageNote":"Osceola county FeatureServer, direct"}, expect: {"pin":"10-003-013-20","lng":1,"lat":1} },
];

/**
 * The declared properties, rendered as source so you can see what each one
 * actually checks. **Read the body, not the name** — a property's name is
 * unchecked prose, and at least one in this repository is named for a check it
 * does not perform.
 *
 * These run against the declared examples here. The acceptance gate also runs
 * them against generated inputs, which is where a property earns its keep.
 */
export const properties: PropertyCheck[] = [
  {
    name: "the centroid lies within the boundary's bounding box",
    // Weaker than point-in-polygon but checkable without a geometry library, and it catches the failure that actually happens: a shoelace implementation that divides by 6*area with the wrong sign, putting the centroid outside the parcel entirely.
    holds: (input, output) => {
      const read = reader(input, output);
      return same(read("output.pin"), read("input.pin"));
    },
  },
];

/**
 * Runs every example and every property, and reports which **artifact** is wrong
 * rather than only that something is.
 *
 * - `input-schema`  the example's own `given` does not satisfy the input
 *                   schema. A declaration bug; your `fn` never ran.
 * - `output-schema` your result is the wrong shape.
 * - `value`         right shape, wrong value.
 * - `threw`         your `fn` declined. Correct for input it cannot handle,
 *                   and a bug on a declared example.
 * - `property`      a declared invariant did not hold.
 */
export function check(): Failure[] {
  const failures: Failure[] = [];

  for (const [i, ex] of examples.entries()) {
    const n = i + 1;

    const parsedInput = parcelCentroidInput.safeParse(ex.given);
    if (!parsedInput.success) {
      failures.push({ example: n, stage: "input-schema", detail: parsedInput.error.message });
      continue;
    }

    let actual: unknown;
    try {
      actual = fn(ex.given as never);
    } catch (cause) {
      failures.push({ example: n, stage: "threw", detail: (cause as Error).message });
      continue;
    }

    const parsedOutput = parcelCentroidOutput.safeParse(actual);
    if (!parsedOutput.success) {
      failures.push({ example: n, stage: "output-schema", detail: parsedOutput.error.message });
      continue;
    }

    if (!same(actual, ex.expect)) {
      failures.push({
        example: n,
        stage: "value",
        detail: `expected ${JSON.stringify(ex.expect)}, got ${JSON.stringify(actual)}`,
      });
      continue;
    }

    for (const property of properties) {
      let held: boolean;
      try {
        held = property.holds(ex.given, actual);
      } catch (cause) {
        // A path that cannot resolve is a broken property — the contract's
        // defect, not yours. Reported separately so it is not read as a
        // violation you caused.
        failures.push({
          example: n,
          stage: "property",
          detail: `"${property.name}" is broken: ${(cause as Error).message}`,
        });
        continue;
      }
      if (!held) {
        failures.push({ example: n, stage: "property", detail: `"${property.name}" did not hold` });
      }
    }
  }

  return failures;
}
