// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { NormalizedParcel } from "../../schemas/NormalizedParcel.js";
import { RawParcelFeature } from "../../schemas/RawParcelFeature.js";

/** What `normalizeParcel` receives, after the membrane has asserted it. */
export const normalizeParcelInput = RawParcelFeature;
export type normalizeParcelInput = z.infer<typeof normalizeParcelInput>;

/** What `normalizeParcel` must return. Throw to decline. */
export const normalizeParcelOutput = NormalizedParcel;
export type normalizeParcelOutput = z.infer<typeof normalizeParcelOutput>;

export type normalizeParcelFn = (p: normalizeParcelInput) => normalizeParcelOutput;
