// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { FactFinding } from "../../schemas/FactFinding.js";
import { FactReport } from "../../schemas/FactReport.js";

/** What `confirmCitations` receives, after the membrane has asserted it. */
export const confirmCitationsInput = FactFinding;
export type confirmCitationsInput = z.infer<typeof confirmCitationsInput>;

/** What `confirmCitations` must return. Throw to decline. */
export const confirmCitationsOutput = FactReport;
export type confirmCitationsOutput = z.infer<typeof confirmCitationsOutput>;

export type confirmCitationsFn = (p: confirmCitationsInput) => confirmCitationsOutput;
