// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { DirectCountyQuery } from "../../schemas/DirectCountyQuery.js";
import { ParcelRequest } from "../../schemas/ParcelRequest.js";
import { ProxiedCountyQuery } from "../../schemas/ProxiedCountyQuery.js";

/** What `routeCounty` receives, after the membrane has asserted it. */
export const routeCountyInput = ParcelRequest;
export type routeCountyInput = z.infer<typeof routeCountyInput>;

/** What `routeCounty` must return. Throw to decline. */
export const routeCountyOutput = z.discriminatedUnion("edge", [
  z.object({ edge: z.literal("DirectCountyQuery"), payload: DirectCountyQuery }),
  z.object({ edge: z.literal("ProxiedCountyQuery"), payload: ProxiedCountyQuery }),
]);
export type routeCountyOutput = z.infer<typeof routeCountyOutput>;

export type routeCountyFn = (p: routeCountyInput) => routeCountyOutput;
