// GENERATED by `weir scaffold` — do not edit.
// The edge schemas live in ../../schemas/, one module each, shared by every
// node that touches them.

import { z } from "zod";
import { FactFinding } from "../../schemas/FactFinding.js";
import { Revision } from "../../schemas/Revision.js";

/** What `checkFacts` receives, after the membrane has asserted it. */
export const checkFactsInput = Revision;
export type checkFactsInput = z.infer<typeof checkFactsInput>;

/** What `checkFacts` must return. Throw to decline. */
export const checkFactsOutput = FactFinding;
export type checkFactsOutput = z.infer<typeof checkFactsOutput>;

export type checkFactsFn = (p: checkFactsInput) => checkFactsOutput;
